config:
  send_anonymous_usage_stats: false

jaffle_shop:
  target: jaffle
  outputs:
    jaffle:
      type: bigquery
      method: oauth
      project: lightdash-database-staging
      dataset: e2e_jaffle_shop
      threads: 1
