config:
  send_anonymous_usage_stats: false

jaffle_shop:
  target: jaffle
  outputs:
    jaffle:
      type: postgres
      host: "{{ var('PGHOST') }}"
      port: "{{ env_var('PGPORT') | as_number }}"
      user: "{{ env_var('PGUSER') }}"
      pass: "{{ var('PGPASSWORD') }}"
      dbname: "{{ env_var('PGDATABASE') }}"
      sslmode: disable
      schema: jaffle
