version: "3.9"
services:
  lightdash:
    image: lightdash/lightdash:latest
    depends_on:
      - db
    environment:
      - LIGHTDASH_DB_HOST=${LIGHTDASH_DB_HOST:-db}
      - LIGHTDASH_DB_PORT=${LIGHTDASH_DB_PORT:-5432}
      - LIGHTDASH_DB_USER=${LIGHTDASH_DB_USER:-postgres}
      - LIGHTDASH_DB_PASSWORD=${LIGHTDASH_DB_PASSWORD}
      - LIGHTDASH_DB_DATABASE=${LIGHTDASH_DB_DATABASE:-postgres}
      - POSTGRES_HOST=${LIGHTDASH_DB_HOST:-db}
      - POSTGRES_PORT=${LIGHTDASH_DB_PORT:-5432}
      - POSTGRES_USER=${LIGHTDASH_DB_USER:-postgres}
      - POSTGRES_PASSWORD=${LIGHTDASH_DB_PASSWORD}
      - POSTGRES_DATABASE=${LIGHTDASH_DB_DATABASE:-postgres}
      - SECURE_COOKIES=${SECURE_COOKIES:-false}
      - TRUST_PROXY=${TRUST_PROXY:-false}
      - LIGHTDASH_SECRET=${LIGHTDASH_SECRET}
      - PORT=${PORT:-8080}
    volumes:
      - "${DBT_PROFILES_DIR}:/usr/app/profiles"
      - "${DBT_PROJECT_DIR}:/usr/app/dbt"
    ports:
      - ${PORT:-8080}:${PORT:-8080}

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${LIGHTDASH_DB_PASSWORD}
      POSTGRES_USER: ${LIGHTDASH_DB_USER:-postgres}
      POSTGRES_DB: ${LIGHTDASH_DB_DATABASE:-postgres}
