version: "3.9"
services:
  lightdash:
    build:
      context: .
    environment:
      - LIGHTDASH_SPAWN_DBT=true
      - DBT_PROJECT_DIR=/usr/app/dbt
      - DBT_PROFILES_DIR=/usr/app/profiles
    volumes:
      - "${DBT_PROFILES_DIR}:/usr/app/profiles"
      - "${DBT_PROJECT_DIR}:/usr/app/dbt"
    ports:
      - 8080:8080