version: "3.9"
services:
  lightdash:
    image: lightdash/lightdash:latest
    environment:
      - LIGHTDASH_SPAWN_DBT=true
    volumes:
      - "${DBT_PROFILES_DIR}:/usr/app/profiles"
      - "${DBT_PROJECT_DIR}:/usr/app/dbt"
    ports:
      - 8080:8080
