previewsEnabled: true

databases:
  - name: jaffle_db
    ipAllowList: []


services:
  - type: web
    env: docker
    name: lightdash
    dockerContext: .
    dockerfilePath: dockerfile-demo
    envVars:
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: jaffle_db
          property: password
      - key: POSTGRES_USER
        fromDatabase:
          name: jaffle_db
          property: user
      - key: POSTGRES_HOST
        fromDatabase:
          name: jaffle_db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: jaffle_db
          property: port
      - key: POSTGRES_DATABASE
        fromDatabase:
          name: jaffle_db
          property: database
      - key: PGHOST
        fromDatabase:
          name: jaffle_db
          property: host
      - key: PGPORT
        fromDatabase:
          name: jaffle_db
          property: port
      - key: PGDATABASE
        fromDatabase:
          name: jaffle_db
          property: database
      - key: PGUSER
        fromDatabase:
          name: jaffle_db
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: jaffle_db
          property: password
      - fromGroup: rudder-settings
      - key: LIGHTDASH_SECRET
        generateValue: true
      - key: SECURE_COOKIES
        value: true
      - key: TRUST_PROXY
        value: true

  - type: web
    name: docsite
    env: static
    buildCommand: cd docs; yarn install; yarn build
    staticPublishPath: docs/build
    pullRequestPreviewsEnabled: true
    envVars:
      - key: RUDDERSTACK_DATAPLANE_URL
        sync: false
      - key: RUDDERSTACK_WRITE_KEY
        sync: false

envVarGroups:
  - name: rudder-settings
    envVars:
      - key: RUDDERSTACK_WRITE_KEY
        value: 1vikeGadtB0Y0oRDFNL2Prdhkbp
      - key: RUDDERSTACK_DATA_PLANE_URL
        value: https://analytics.lightdash.com
