version: "3.9"
services:
  lightdash:
    build:
      context: .
      dockerfile: dockerfile
    depends_on: 
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=postgres
    volumes:
      - "./profiles:/usr/app/profiles"
      - "./dbt:/usr/app/dbt"
    ports:
      - 8080:8080

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
