version: "3.9"
services:
  lightdash:
    build:
      context: .
      dockerfile: dockerfile-lightdash-demo
    depends_on: 
      - db
    environment:
      - LIGHTDASH_SPAWN_DBT=true
      - DBT_PROJECT_DIR=/usr/app/dbt
      - DBT_PROFILES_DIR=/usr/app/profiles
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=postgres
    volumes:
      - "./profiles:/usr/app/profiles"
      - "./dbt:/usr/app/dbt"
    ports:
      - 8080:8080

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
