version: "3.8"
services:
  lightdash-dev:
    build:
      context: ..
      dockerfile: dockerfile
      target: ${DOCKERFILE_TARGET}
    depends_on:
      - db-dev
    environment:
      - PGHOST=${PGHOST}
      - PGPORT=${PGPORT}
      - PGUSER=${PGUSER}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
      - RUDDERSTACK_WRITE_KEY=${RUDDERSTACK_WRITE_KEY}
      - RUDDERSTACK_DATA_PLANE_URL=${RUDDERSTACK_DATA_PLANE_URL}
      - SECURE_COOKIES=${SECURE_COOKIES}
      - LIGHTDASH_SECRET=${LIGHTDASH_SECRET}
      - SENTRY_DSN=${SENTRY_DSN}
      - NODE_ENV=${NODE_ENV}
      - LIGHTDASH_CONFIG_FILE=${LIGHTDASH_CONFIG_FILE}
      - DBT_DEMO_DIR=${DBT_DEMO_DIR}
      - LIGHTDASH_PROTOCOL=${LIGHTDASH_PROTOCOL}
      - LIGHTDASH_HOST=${LIGHTDASH_HOST}
      - EMAIL_SMTP_HOST=${EMAIL_SMTP_HOST}
      - EMAIL_SMTP_PORT=${EMAIL_SMTP_PORT}
      - EMAIL_SMTP_SECURE=${EMAIL_SMTP_SECURE}
      - EMAIL_SMTP_USER=${EMAIL_SMTP_USER}
      - EMAIL_SMTP_PASSWORD=${EMAIL_SMTP_PASSWORD}
      - EMAIL_SMTP_ALLOW_INVALID_CERT=${EMAIL_SMTP_ALLOW_INVALID_CERT}
      - EMAIL_SMTP_SENDER_NAME=${EMAIL_SMTP_SENDER_NAME}
      - EMAIL_SMTP_SENDER_EMAIL=${EMAIL_SMTP_SENDER_EMAIL}
    volumes:
      - "../:/usr/app"
    ports:
      - "${PORT}:8080"
      - "3000:3000"
    command: ""
    entrypoint: ["/bin/sh", "-c", "sleep infinity"]

  db-dev:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports:
      - "5432:${PGPORT}"
