version: "3.8"
volumes:
  node_modules:

services:
  lightdash-dev:
    build:
      context: ..
      dockerfile: dockerfile
      target: dev
    depends_on:
      - db-dev
    environment:
      - PGHOST=db-dev
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=password
      - PGDATABASE=postgres
      - RUDDERSTACK_WRITE_KEY=1vikeGadtB0Y0oRDFNL2Prdhkbp
      - RUDDERSTACK_DATA_PLANE_URL=https://analytics.lightdash.com
      - SECURE_COOKIES=false
      - LIGHTDASH_SECRET="not very secret"
      - LIGHTDASH_LOG_LEVEL=debug
      - NODE_ENV=development
      - LIGHTDASH_CONFIG_FILE=/usr/app/lightdash.yml
      - DBT_DEMO_DIR=/usr/app/examples/full-jaffle-shop-demo
      - AUTH_DISABLE_PASSWORD_AUTHENTICATION=false
      - AUTH_ENABLE_GROUP_SYNC=false
      - SITE_URL=http://localhost:3000
      - ALLOW_MULTIPLE_ORGS=false
      - LIGHTDASH_QUERY_MAX_LIMIT=5000
      - HEADLESS_BROWSER_HOST=headless-browser
      - HEADLESS_BROWSER_PORT=3000
      - SCHEDULER_ENABLED=true
      - GROUPS_ENABLED=true
    volumes:
      - "../:/usr/app"
      - "../examples/full-jaffle-shop-demo/dbt:/usr/app/dbt"
      - "node_modules:/usr/app/node_modules/" # clears the node_modules directory so it doesn't sync (v.slow on MacOS)
    ports:
      - "8080:8080"
      - "3000:3000"
    command: ""
    entrypoint: [ "/bin/sh", "-c", "sleep infinity" ]
  db-dev:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  headless-browser:
    image: browserless/chrome
    restart: always
    ports:
      - "3001:3000"

  jaeger:
    image: jaegertracing/all-in-one:1.50
    restart: always
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411