name: Deploy to docker hub

on:
  pull_request:
    branches:
      - 'main'
  push:
    tags:
      - '*'
      - '!*-alpha*'
      - '!*-beta*'

  workflow_dispatch:


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Setup docker tags
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            lightdash/lightdash
          tags: |
            type=semver,pattern={{version}}
      # Improved docker builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      # Credentials for pushing final image to docker hub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      # Build image and push to docker hub
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
