name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
      
    - name: Lint all packages
      run: yarn lint
    - name: Check formatting all packages
      run: yarn format
    - name: Check for unused exports
      run: yarn workspace frontend unused-exports 

    - name: Build common
      run: yarn common-build

    - name: Build warehouses
      run: yarn warehouses-build

    - name: Run unit tests
      run: yarn backend-build && yarn test

