name: Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            # Install packages
            - uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'yarn'
            - name: Install packages
              run: yarn install --frozen-lockfile
            - name: Run dangerjs
              # Ensure the dangerjs check only runs on internal pull requests, while allowing
              # us to reuse the remainder of the setup for this workflow:
              #
              # If we ever migrate this away from this action, `pull_request_target` solves for
              # this problem out of the gate, and is a cleaner solution.
              if: |
                  github.event_name == 'pull_request' &&
                  ${{ github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name }}
              run: yarn danger-ci-lint
              env:
                  GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
            - name: Lint all packages
              run: yarn lint
            - name: Check formatting all packages
              run: yarn format
            - name: Check for unused exports
              run: yarn workspace frontend unused-exports

            - name: Build common
              run: yarn common-build

            - name: Build warehouses
              run: yarn warehouses-build

            - name: Run unit tests
              run: yarn backend-build && yarn test
