name: test pr user
on:
  push:
    branches-ignore: [ "main", "master" ]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: View PR author
        run: echo "github.actor ${{github.actor}} ."
      - name: View PR author
        run: echo "github.event.pull_request.user.login ${{github.event.pull_request.user.login}} ."
