name: test pr user
on: [ deployment_status ]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR number
        id: regex
        uses: AsasInnab/regex-action@v1
        with:
          regex_pattern: '[0-9]+$'
          regex_flags: 'gm'
          search_string: ${{github.event.deployment.environment}}
      - name: View PR author
        run: echo "This PR is opened by ${{github.actor}} ."
